### PR TITLE
Hamburger menu

### PR DESCRIPTION
**Pull request by kart-c**
## Hamburger menu

- Add functionality to the hamburger menu button in the navbar component

[CSB for reference](https://xp95y2.csb.app/Components/Navigation/navigation.html)

### CODE REVIEW

**Review by Abhijeet43 — CHANGES_REQUESTED** [review]
- When in Navigation page active state is also visible on range 
active

**Review by Abhijeet43 — CHANGES_REQUESTED** [review]
The link to navigation page in range slider is not working correctly

**Comment by kart-c** [comment]
> * When in Navigation page active state is also visible on range
>   active

Fixed it. Thanks for pointing it out!

**Comment by kart-c** [comment]
> The link to navigation page in range slider is not working correctly

Fixed it 🚀

**Review by Abhijeet43 — APPROVED** [review]
- The functionality is working as intended
- Really liked you have a seperate html for mobile nav
- Naming Conventions are good
- Suggestions: You could use transition over mobile menu.. to make pop up smooth, Code can be better formatted

**Review by AtulPant2704 — APPROVED** [review]
Functionality is working fine and variable naming is also good.

**Pull request merged**
