### PR TITLE
Add Card component

### PR DESCRIPTION
**Pull request by kart-c**
## Attached a csb link for review

https://vx663.csb.app/Card/card.html

User has a choice to use either border on cards or the box shadow by using the `card-shadow` class

### CODE REVIEW

**Comment by SatwikaKacham** [comment]
the code is neat and cards looks great. one suggestion write comment messages between card to differentiate .Approving it

**Comment by AnkurChunekar** [comment]
kartik review
Hey, Great work. I have a feedback, If possible you can add some border to cards because of the same color it's hard to guess the width and everything around. Rest everything looks great.

**Review by AnkurChunekar — APPROVED** [review]

**Review by mohammed-sas — APPROVED** [review]
you're code is good to merge

**Comment by kart-c** [comment]
> kartik review Hey, Great work. I have a feedback, If possible you can add some border to cards because of the same color it's hard to guess the width and everything around. Rest everything looks great.

Thanks Ankur I will change that

**Review by Abhijeet43 — APPROVED** [review]
Code looks good

**Review by AnkurChunekar — APPROVED** [review]

**Pull request merged**
